Added DBUIQuit command
kristijanhusak/vim-dadbod-ui pull request #156
Opened 2023-02-12 21:14 UTC by bgfxc4

Added the command, because I want to be able to close the DBUI when opening nvim-tree to only have one sidebar opened.

2023-02-12 21:37 UTC, kristijanhusak requested changes

2023-02-12 21:37 UTC, kristijanhusak commented on plugin/db_ui.vim
> +command! DBUIQuit call db_ui#quit()
Lets call it `DBUIClose` and the function `db_ui#close()`, just to have it properly as an opposite of `open`.

2023-02-12 21:42 UTC, kristijanhusak approved these changes

2023-02-12 21:42 UTC, merged

2023-02-12 21:42 UTC, kristijanhusak commented
Thanks!

2023-02-14 06:22 UTC, ueaner commented
> Added the command, because I want to be able to close the DBUI when opening nvim-tree to only have one sidebar opened.

Looking forward to your works.
I have a question, do I need to check if `dbui` is open?

2023-02-14 10:31 UTC, kristijanhusak commented
> > Added the command, because I want to be able to close the DBUI when opening nvim-tree to only have one sidebar opened.
> 
> Looking forward to your works. I have a question, do I need to check if `dbui` is open?

There's no need for that.

2023-02-14 15:32 UTC, ueaner commented
> > do I need to check if `dbui` is open?
> 
> There's no need for that.

Thank you for your reply.
I made an implementation based on the open state of dbui.

https://github.com/ueaner/nvimrc/blob/0c75033f981f4e171c6b87550bc186bffaaef6e7/lua/utils.lua#L76-L119

Am I missing something?
Can you share your approach?